classification: packaging
color: ''
description_extra: ''
description_main: hinged_lid
id: packaging_takeaway_container_circle_60_ml_hinged_lid_majestic_05390_pv22
manufacturer: majestic
part_number: 05390_pv22
size: 60_ml
type: takeaway_container_circle
