classification: packaging
color: brown
description_extra: ''
description_main: ''
id: packaging_cardboard_box_postal_tabs_c4_324_mm_width_229_mm_height_50_mm_depth_brown
manufacturer: ''
part_number: ''
size: c4_324_mm_width_229_mm_height_50_mm_depth
type: cardboard_box_postal_tabs
