classification: packaging
color: brown
description_extra: ''
description_main: ''
id: packaging_cardboard_box_postal_tabs_imperial_7_in_x_5_in_x_2_in_brown
manufacturer: ''
part_number: ''
size: imperial_7_in_x_5_in_x_2_in
type: cardboard_box_postal_tabs
