classification: packaging
color: brown
description_extra: ''
description_main: ''
id: packaging_cardboard_box_postal_tabs_imperial_7_in_width_5_in_height_2_in_depth_brown
manufacturer: ''
part_number: ''
size: imperial_7_in_width_5_in_height_2_in_depth
type: cardboard_box_postal_tabs
