classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_takeaway_container_rectangle_500_ml_nisbet_fiesta_small_dm181
manufacturer: nisbet_fiesta
part_number: small_dm181
size: 500_ml
type: takeaway_container_rectangle
