classification: packaging
color: ''
description_extra: ''
description_main: hinged_lid
id: packaging_takeaway_container_circle_30_ml_hinged_lid_majestic_05385_pv11
manufacturer: majestic
part_number: 05385_pv11
size: 30_ml
type: takeaway_container_circle
