classification: packaging
color: ''
description_extra: ''
description_main: hinged_lid
id: packaging_takeaway_container_circle_120_ml_hinged_lid_majestic_05390_pv44
manufacturer: majestic
part_number: 05390_pv44
size: 120_ml
type: takeaway_container_circle
