classification: packaging
color: brown
description_extra: ''
description_main: ''
id: packaging_cardboard_box_postal_tabs_c6_162_mm_width_114_mm_height_50_mm_depth_brown
manufacturer: ''
part_number: ''
size: c6_162_mm_width_114_mm_height_50_mm_depth
type: cardboard_box_postal_tabs
