classification: packaging
color: ''
description_extra: ''
description_main: heavy_duty
id: packaging_takeaway_container_circle_60_ml_heavy_duty_satco
manufacturer: satco
part_number: ''
size: 60_ml
type: takeaway_container_circle
