classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_tin_hinged_lid_169_mm_width_130_mm_height_18_mm_depth_350_ml_tinware_direct_t4066
manufacturer: tinware_direct
part_number: t4066
size: 169_mm_width_130_mm_height_18_mm_depth_350_ml
type: tin_hinged_lid
