classification: packaging
color: clear
description_extra: ''
description_main: 88_mm_width_114_mm_height
id: packaging_bag_grip_seal_75_micron_thickness_clear_88_mm_width_114_mm_height_kite_packaging_pbrh3_5_x_4_5
manufacturer: kite_packaging
part_number: pbrh3_5_x_4_5
size: 75_micron_thickness
type: bag_grip_seal
