classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_tin_hinged_lid_a5_220_mm_width_160_mm_height_25_mm_depth_450_ml_tinware_direct_t4005
manufacturer: tinware_direct
part_number: t4005
size: a5_220_mm_width_160_mm_height_25_mm_depth_450_ml
type: tin_hinged_lid
