classification: packaging
color: brown
description_extra: ''
description_main: ''
id: packaging_cardboard_box_postal_tabs_c5_229_mm_x_162_mm_x_50_mm_brown
manufacturer: ''
part_number: ''
size: c5_229_mm_x_162_mm_x_50_mm
type: cardboard_box_postal_tabs
