classification: packaging
color: clear
description_extra: ''
description_main: 88_mm_width_114_mm_height
id: packaging_bag_grip_seal_45_micron_thickness_clear_88_mm_width_114_mm_height_kite_packaging_pbr3_5_x_4_5_kite
manufacturer: kite_packaging
part_number: pbr3_5_x_4_5_kite
size: 45_micron_thickness
type: bag_grip_seal
