classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_takeaway_container_rectangle_1000_ml_nisbet_fiesta_large_dm183
manufacturer: nisbet_fiesta
part_number: large_dm183
size: 1000_ml
type: takeaway_container_rectangle
