classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_takeaway_container_rectangle_650_ml_nisbet_fiesta_medium_dm182
manufacturer: nisbet_fiesta
part_number: medium_dm182
size: 650_ml
type: takeaway_container_rectangle
