classification: packaging
color: ''
description_extra: ''
description_main: ''
id: packaging_takeaway_container_circle_150_ml_nisbet_fiesta_ct083
manufacturer: nisbet_fiesta
part_number: ct083
size: 150_ml
type: takeaway_container_circle
